### ISSUE TITLE
Eingabefläche

### ISSUE THREAD

**Issue by SimonThormeyer** [SimonThormeyer/beuthSoundGroup#1]
Als BenutzerIn möchte auf eine Eingabeflaeche klicken koennen, damit ein Ton erzeugt wird. 

**Beschreibung**

Eine klickbare Fläche soll es dem/der BenutzerIn ermöglichen, durch Klicken Töne zu erzeugen, die je nach Position eine andere Frequenz haben.
Dazu sollen erstmal Sinus-Töne einer bestimmten Frequenz ausgegeben werden und dann (wenn möglich) mithilfe von Tone.js Klaviertöne.

**Akzeptanzkriterien**

**Tasks**
- [x] React-Komponente erstellen (#14 )
- [x] Eingaben auf dem Viewport einfangen (#14 )
- [x] Komponente eines Synthesizers erstellen (#17)

**Story Points**
/estimate 13
