### ISSUE TITLE
Random Notes (SP.5)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#108]
As an User, I want to have the computer create random notes.

**description of the story**

A click on the "random notes"-button triggers a function that creates random notes. These notes are also shown on the canvas.

**acceptance criteria**
- [x] The "random notes"-button triggers random notes
- [x] These notes are also shown on the canvas

**tickets or tasks**
- [x] Create the functionality (#113 )
- [x] create a random time function that triggers a note in random time distances (#113 )
- [x] create a random note function that triggers a random note to be triggered in random time distances (#113 )

**story points**
/estimate 5
