### ISSUE TITLE
Optimization (SP. 20)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#116]
As a developer I want the app to run smoothly and without tone-crackings.

**description of the story**

This might cover all we need:
https://tonejs.github.io/docs/13.8.25/Context.html#latencyhint 

Especially on slower machines and when moving the three dots the sounds starts to crack. This cracking is permanent after that.
The development team should be optimising their written code as much as possible and the project shoud be optimised by "Throttling and Debouncing" (https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf) it.
One solution could be to reduce the effects to an amount where there is no cracking and then enrich the sound possibilities for the user with multitracking.

But the way to an optimized app is through many small changes in many functionalities.

**acceptance criteria**
- [x] No cracking when testing the project
- [x] Also slow machines should have no problem running this app
- [x] The user shouldn't be able to crash the app by their input

**tickets or tasks**
- [x] investigate on the causes of the unwanted sound artifacts
- [x] find a good value for [Tone.Contex.latencyhint](https://tonejs.github.io/docs/13.8.25/Context.html#latencyhint) and [Tone.Context.lookAhead](https://tonejs.github.io/docs/13.8.25/Context.html#lookahead)
- [x] Make sure that the sound never overdrives (#128 )
- [x] Try a low performance canvas (#130 )
- [x] Optimise the canvas with Three.js-Fiber (#173 )
- [x] Prohibit actions that lead to lags or even crash the app (#209 , #169 , #163 )
- [x] Start the app and the functionalities only when all required functions are loaded and ready (#171 , #169 )

**Comment by MalteMittrowann** [comment]
This epic is done and the app is optimized for the final presentation!
