### ISSUE TITLE
canvas resizing (SP.8)

### ISSUE THREAD

**Issue by chanty1512** [SimonThormeyer/beuthSoundGroup#124]
As a user, I want to be able to resize the screen and get a responsive layout so I don't have to reload the screen all the time

**acceptance criteria**
- [x] the canvas size changes on resize
- [x]  the screen doesn't load every time on resizing

**tasks**
- [x] add a use effect that listens to screen width/heigth #129
