### ISSUE TITLE
Rescaling and mobile versions (Epic #132)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#133]
### Description

The user interface has to be optimized for the mobile view because the user wants to use the web app from 
his mobile phone

### Related Issue
If the smartphone is used, the size of the icons, text and buttons must be adjusted

### To Do:

- [x] hover loop icons
- [x] size of icons
- [x] size of text
- [x] size of buttons

### How Has This Been Tested?

- [x] mobile versions
- [x] resized canvases
