### ISSUE TITLE
Random dots movement (SP.39)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#136]
As an User, I want to randomise the parameter dots, so that I can get a greater variety and freedom in the sounds created by the app

**description of the story**

The three dots should be randomisable with the randomNotesAndDotsFunction.
For this we use the **React Spring**-library.

**acceptance criteria**
- [x] After clicking on the randomNote-Button, the three dots on this canvas should move independently from each other

**tickets or tasks**
- [x] first POC for moving the dots (#156 )
- [x] Move all dots at the same time (#156)
- [x] Move the dots independently from each other and in a fun way (#166 )
- [x] Create a seperate randomNotesAndDots-Function for every canvas (#183 )

**story points**
/estimate 39

**Comment by MalteMittrowann** [comment]
Completed
