### ISSUE TITLE
Multitracking (SP. 13)

### ISSUE THREAD

**Issue by chanty1512** [SimonThormeyer/beuthSoundGroup#139]
As an User, I want to change the Synthesizers and enable multitracking to enhance music playground functionality

**description of the story**
On click at arrows the user can swith through diffrent canvas and synthesizers. previous loops music keeps playing. 

**blocked by**
- [x] #140

**acceptance criteria**
- [x] visual icons to switch canvas
- [x] create new canvas by switching 
- [x] keep previous canvas with loops..
- [x] the switch between the canvases is supported by a visual feedback
- [x] every track has an own **randomNotesAndDotsMovement-Function**

**tickets or tasks**
- [x] visual icons to switch canvas (#140)
- [x] make switching canvases and musicCtrls possible (#152)
- [x] every track gets an own **randomNotesAndDotsMovement-Function** (#183 )

**story points**
/estimate 13

**Comment by chanty1512** [comment]
gerne noch weite punkte hinzufügen. habe nas angelegt für die visuellen navigations icons zum wechseln zwischen den canvas

**Comment by MalteMittrowann** [comment]
Opening this up again to give a user story to the implementation of the visual part of the **multitracking**.

**Comment by MalteMittrowann** [comment]
Done
