### ISSUE TITLE
Environment Variables (Backend-URL) (SP 7) (EPIC #132)

### ISSUE THREAD

**Issue by SimonThormeyer** [SimonThormeyer/beuthSoundGroup#145]
As a developer, I want the communication with the backend to work in production.

**description of the story**

Detailed Description of the User-Story:
If the URL of backend is set to http://localhost:5000" when sending requests (as it currently is), sending requests from frontend to backend will not work when accessing the WebApp on our server, as the host (from perspective of frontend) is supposed to be:
"terry.beuth-media.de" (or "80.190.117.183" until we have our reverse proxy set up and working) not "localhost", which refers to the **_local machine of the user_**, not **_our server_**.
This can be set up in an .env-file (which should be added to .gitignore) and refered to as process.env.BACKEND_URL in frontend.

**acceptance criteria**
- [x] storing and loading projects works in production just like locally when testing during development 

**tickets or tasks**
- [x] create .env file in Frontend folder (maybe it's best to have .env.development and .env.production, please do research how this should be done and how one can switch environments - probably the command for switchting to production environment has to be included in Dockerfile in frontend)  
- [x] add BACKEND_URL='http://terry.beuth-media.de/db/' (for example, or whatever path our reverse proxy is proxying from to the backend) to the file (or "http://80.190.117.183:5000" until we have our reverse proxy set up and working) 
- [x] replace all 'http://localhost:5000' references in Frontend with process.env.BACKEND_URL
- [x] add .env to .gitignore, then change BACKEND_URL back to "http://localhost:5000" on your machine so you can keep testing your local backend during development

**story points**
/estimate 7
