### ISSUE TITLE
Random moving dots (part of epic #136) (SP 13)

### ISSUE THREAD

**Issue by LucaPomer** [SimonThormeyer/beuthSoundGroup#156]
As a User, I want to be able to let the dots move randomly to allow me to concentrate on the notes while playing with Terry or to not control Terry all the time with full attention.

**description of the story**

For the Random Moving Dots Function we will implement a function that can move the dots on a function call. It moves the dots in a random manner.

**acceptance criteria**
- [x] the dot should be able to move on a function call
- [x] the function is triggered with the random notes button
- [x] the dots move randomly, but do not leave the canvas

**tickets or tasks**
- [x] Create a function that moves a dot according to coordinates (#166 )
- [x] Move dots randomly on the canvas (#166 )
- [x] make sure the dots stay on the canvas (#166 )
- [x] call and toggle the function with the "Random Notes"-Button (#166 )

**story points**
/estimate 13

**Comment by SimonThormeyer** [comment]
https://use-gesture.netlify.app/docs/options/#initial
