### ISSUE TITLE
Mapping von der Eingabekoordinaten auf ein Isomorphes Modell

### ISSUE THREAD

**Issue by fr3ddykrueger** [SimonThormeyer/beuthSoundGroup#18]
Als Entwickler möchte ich die Eingabe auf ein Isomorphes model mappen, um ein nicht lineare Eingabe zu erhalten.

**description of the story**
Die Eingabe aus dem View bzw. React wird auf isomorphes Modell gemappt und ein Notennname ausgegeben.

**blocked by**
#1 
**acceptance criteria**
- [x] Je nach Position des Klicks wird ein anderer Notenname ausgegeben, der in das Tonmaterial einer Tonart passt.
- [x] Links unten tiefe Töne
- [x] Rechts oben hohe Töne

**Tickets or Tasks**
- [x] Model für das mappen von Koordinaten auf Frequenzen (Isomorphic Note Layout) (#15 )
- [x] Eingabekoordinaten werden als relative Werte zwischen 0-1 vom Canvas ausgegeben (#35)
- [x] Notennamen in Abhängigkeit von der Position ausgeben (#31)

**Story Points**
