### ISSUE TITLE
Separate Random-Notes-Function for every canvas (EPIC #139)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#183]
As an User, I want to have a separate Random-Notes-Function for every canvas, so that what I see corresponds to what I hear and so that I can randomize every of the three sounds.

**description of the story**

Every canvas gets a separate button for the **Random Notes Function** and this will trigger the function for this canvas, separate from the other canvases.

**acceptance criteria**
- [x] Every canvas has a working button for the function
- [x] This function triggers random notes on this specific canvas

**tickets or tasks**
- [x] Separate function for every canvas (#184 )

**story points**
/estimate 7
