### ISSUE TITLE
visuell slide function to switch canvas (User Story #139)

### ISSUE THREAD

**Issue by chanty1512** [SimonThormeyer/beuthSoundGroup#214]
As a user I want a slide function when switching between canvases so that I can get a visual feedback for this action

**Description:**
To visually switch the individual canvas by clicking on the switch arrow, a slide animation should be added

**Acceptance Criteria:**

- [ ] When switching between canvases there is a slide animation as a feedback for this action
- [ ] This animation does not slow down the switching between the canvases

**ToDo's:**
- [ ] slide animation when clicking on the multitracking arrow

**Comment by MalteMittrowann** [comment]
This functionality will not be implemented for the final presentation of the project module
