### ISSUE TITLE
Deployment (1.SP)

### ISSUE THREAD

**Issue by lunarie16** [SimonThormeyer/beuthSoundGroup#23]
As a teacher I want to have a final delivery, so that I can evaluate the final product.

**Description**

Due to the complexity of this very user story, it might be useful to mark it as an epic. The final delivery shall be provided via moodle and consists of the following:

**Acceptance Criteria**

* document (https://docs.google.com/document/d/1gNbDWnfG2XYfQ0mv_7O8C_f_1vBEPz7e6KR4NqSd_Is/edit?usp=sharing):
* presetation (https://docs.google.com/presentation/d/14LLXxamcnlYgP_9Jf1PfwWkRpEX-_euOPCaudFMBc24/edit)

- [x] cover sheet with group name
- [x] group members
- [x] description of your project
- [x] screen shot of the running application
- [x] links to all sources
- [x] links to the task board
- [x] link to deployed running application
- [x] usage instructions for a typical use case with expected results (e.g. a prepared user login for the teachers)
- [x] Presentation as a PDF (#123 )
* [ ] option 1: software as archive
 * final product as archive
 * installation script for final product
* [x] option 2: software as source
 * links to release or master branches
 * installation scripts for your sources
* [x] optional, but recommended:
 * provide deployment scripts

**blocked by**
#116 , #9 , #132 

**Story Points**
/estimate 26

**Comment by MalteMittrowann** [comment]
DONE!

![image](https://user-images.githubusercontent.com/43847487/87783764-6a45c280-c835-11ea-8279-0d39f9ea4352.png)
