### ISSUE TITLE
visuelle Menuleiste

### ISSUE THREAD

**Issue by chanty1512** [SimonThormeyer/beuthSoundGroup#28]
Als Benutzer möchte ich ein Menü mit Buttons für die Interaktion in der WebApp haben, weil ich play, record, loop und random musik spielen möchte.

**Akzeptanzkriterien:**
- [x] vier Buttons zu sehen (Loop, Record, Play, Random)
- [x] beim Klicken veränderung des Buttons
- [x] pro Button Methode aufrug um tone.js anzusprechen

**Tasks:**
- [x] Icons als Buttons einfügen
- [x] Function schreiben um Icons beim Klicken zu ändern
- [x] Function schreiben um den Klicken auf Icons an Tone.js weiterzuleiten

**Geschätzter Aufwand:**
1 Woche

**Comment by SimonThormeyer** [comment]
Ich habe schon fertige React-Komponenten, die Bootstrap benutzen, die könnten wir kopieren....
