### ISSUE TITLE
store and load Projectstate (SP.13)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#4]
As a developer i want a storeable state of my project, so that i have an overview of the Data and Logic of the App.

**description of the story:**

Due to keep an overview of the data and settings that we create and edit, we need  rational and efficient logic. 
In addition, users should be able to save their settings and inputs in a future version.
In preparation, we always need an efficiently storable state of the entries made with our app.

**acceptance criteria**
- [x] all relevant parts of the global state are exported to the database
- [x] a JSON with those parts is sent to the API
- [x] a project can be selected and loaded from database

**tasks**

- [x] initiate a global State #97 
- [x] the possibility to store the state #97 
- [x] a JSON is sent to API #97 
- [x] there is a nice button and overlay #97 
- [x] there is an input field for projectname and user name / ID #97 
- [x] add dot positions to exported JSON #109 
- [x] implement rehydration #127 
 

**story points:**
13

**Comment by SimonThormeyer** [comment]
Ich würde vorschlagen, dass der Zustand in einem JSON-Objekt speicherbar ist und ins Frontend über den React-Hook 'useState' übertragen wird

**Comment by SimonThormeyer** [comment]
Hier wird gut beschrieben, wie man eine Flask-API mit dem Frontend verbindet
https://www.youtube.com/watch?v=06pWsB_hoD4
