### ISSUE TITLE
Speicherung von Projekten in einer Datenbank (SP.40)

### ISSUE THREAD

**Issue by lunarie16** [SimonThormeyer/beuthSoundGroup#48]
Als BenutzerIn möchte ich meine Projekte in einer Datenbank speichern, sowie in zuvor erstellten Projekten stöbern.

**Beschreibung**

Das Projekt soll mit einem User-Kürzel sowie einem Projektnamen in die Datenbank abgespeichert werden. 
Man soll schon vorhanden Projekten sehen und in ihnen mit Filtern Suchen können. 
**Filter**: user_ID, project_name, user_ID && project_name

**Voraussetzungen / blocked by**
- [x] ein speicherbarer Zustand der Projekte ist vorhanden (#4)

**Akzeptanzkriterien**
- [x] man kann mittels HTTP-Requests auf die Datenbank zugreifen

**Tasks**
- [x] Backend HTTP Routen erstellen (#30 )
- [x] Dantenbank aufbauen
- [x] Projekte als JSON-Objekt 

**Story Points**
/estimate 13
