### ISSUE TITLE
Entwurf vom Looper

### ISSUE THREAD

**Issue by fr3ddykrueger** [SimonThormeyer/beuthSoundGroup#50]
Als Entwickler möchte ich ein Entwurf fuer den Looper haben um eine Uebersicht ueber Schnittstellen und speicherbaren Parametern erhalten. 

**Beschreibung**
Ein Diagramm was die einzelnen komponenten beschreibt und nachvollziehbar

**Akzeptanzkriterien**
- [x] Es ist ersichtlich wie der Looper die komponenten anordnet und mischt
- [x] Die Einzelnen Komponenten koennen gespeichert werden

**Tasks**
- [x] Diagramm des Loopers erstellen #55 
- [x] Looperkomponente erstellen #55 
(- [ ] Diagramm des Synthesizers erstellen ) in einer neue Userstory verschieben
(- [ ] Einzelne Komponente haben Parameter) in einer neue Userstory verschieben

**Story Points**
/estimate 13
