### ISSUE TITLE
DotParameter visualisation (SP.20) 

### ISSUE THREAD

**Issue by fr3ddykrueger** [SimonThormeyer/beuthSoundGroup#69]
As a user, I want to use dots to change the parameters of the sound because it gives me creative freedom.

**Description of the story**
On the canvas there are dots that can be moved around.

**blocked by**

**acceptance criteria**
- [x] there are movable points on the screen
- [x] the movements coordinates are passed on 

**tickets or tasks**
- [x] create 3 movable spheres #75 
- [x] make them nice #76 
- [x] make the change of movement accessible #77 

**story points**
20
