### ISSUE TITLE
Harmonie-Parameter (SP.13)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#8]
Als Benutzer möchte ich Harmonie-Parameter verändern können, um die verwendeten Töne und die Stimmung einstellen zu können.

**is blocked by: #1**

**Beschreibung:**

Ein Punkt auf der Eingabefläche kann verschoben werden, um die Tonauswahl und damit die Stimmung der ausgegebenen Musik einstellen zu können.

**Akzeptanzkriterien:**

- [x] Auf dem Eingabefeld wird ein Punkt erstellt (#69  )
- [x] Dieser Punkt ist vom Benutzer mit der Maus und durch Touch verschiebbar (#69  )
- [x] Die Position des Punktes wird beim Verändern gespeichert (#69  )
- [x] Ein Modell zum Umwandeln der Position in ein Tonmaterial-Modell muss entwickelt werden (#81 )
- [x] Durch Verschieben des Punktes verändert sich die Tonauswahl aus denen eingegebene Töne abgespielt werden (#81 )
- [x] Sowohl für horizontales Verschieben (#81 )
- [x] alsauch für vertikales Verschieben (#81 )
- [x] die ausgegebenen Skalen sind sinnvoll (#81 )

**Geschätzter Aufwand:**

Story-Points: 13
