### ISSUE TITLE
Notes Looper

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#9]
As a user I want to be able to loop the melodies and settings that I put in, so that I can hear my input repeated as a loop and so that I can save my input and therefor stack layers of inputs over one another.

**Description:**

* A looper can save the input melodies and settings and can give them back repeatedly.
* The loops can be muted, paused and deleted.
* The loops are part of the saveable state of all the inputs of the user.
* The looper should run smoothly and without any disturbing artefacts visually as well as auditive.

**Acceptance criteria:**

- [x] A looper button is placed at a appropriate spot on the screen (#79 )
- [x] A concept of how the looper is set up and programmed is made (#50 )
- [x] A melody input can be saved by the looper (#55 )
- [x] The melody input is repeated and looped (#55 )
- [x] Running loops are shown as buttons on the screens that represent the state of the loop (#79 )
- [x] Running loops can be muted (#80 )
- [x] Runing loops can be paused (#80 )
- [x] The loops are part of the saveable state of the user inputs (#4 )
- [x] There should be no glitches or unwanted artefacts visually and auditively and the loops should run smoothly
